### ISSUE TITLE
Anchors/hyperlinks for standards

### ISSUE THREAD

**Issue by noamross** [ropenscilabs/statistical-software-review-book#32]
Because discussions of standards will frequently reference them, it would be good if each standard  (e.g. **G1.2.1**) had an anchor and was a hyperlink to itself so one can link to the standard in discussions about standard revisions or in reviews (or even in automated reports).

**Comment by mpadge** [comment]
TODO:

- [ ] General
- [ ] Bayesian
- [ ] EDA
- [ ] ML
- [ ] Regression
- [ ] Spatial
- [ ] Time Series
- [ ] Unsupervised Learning
